In [247]:
"""This is my model training notebook"""

'This is my model training notebook'

In [248]:
##Import Libraries
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
from math import radians
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsRegressor

In [249]:
##Load the data
dataset = '../../data/properties_working.csv'
df = pd.read_csv(dataset)
df.shape

(3585, 99)

In [250]:
##Drop columns that won't be used for modeling
df_working = df.drop(['immowebCode', 'priceString', 'country', 'locality', 'street', 'availableDate', 'neighborhoodOrLocality', 'floor', 'internet'], axis=1)
##Transform postal code into categorical data
df_working['postalCode'] = df_working['postalCode'].astype(int)
df_working['postalCode'] = df_working['postalCode'].astype(str)
print(df_working.columns)

Index(['type', 'price', 'province', 'district', 'postalCode', 'latitude',
       'longitude', 'constructionYear', 'floor', 'numberOfFloors',
       'buildingCondition', 'numberOfFrontages', 'outdoorParkingSpaces',
       'surroundingsType', 'livingArea', 'livingRoomSurface', 'kitchenType',
       'kitchenSurface', 'bedrooms', 'bedroom1Surface', 'bedroom2Surface',
       'bathrooms', 'toilets', 'basement', 'furnished', 'terraceSurface',
       'elevator', 'disabilityAccess', 'tvCable', 'visioPhone', 'swimmingPool',
       'energyConsumption', 'energyClass', 'EPCReportReference', 'CO2Emission',
       'yearlyEnergyConsumption', 'heatingType', 'thermicSolarPanels',
       'doubleGlazing', 'planningPermission', 'subdivisionPermit',
       'floodZoneType', 'landUseDesignation', 'cadastralIncome',
       'tenementBuilding', 'streetFrontageWidth', 'coveredParkingSpaces',
       'basementSurface', 'monthlyCharges', 'diningRoom', 'showerRooms',
       'intercom', 'bedroom3Surface', 'armoredDoor

In [262]:
df_working['numberOfFloors'].unique()

array(['7', 'None', '2', '3', '8', '6', '4', '17', '5', '13', '10', '12',
       '9', '1', '11', '26', '15', '16', '14', '42', '19', '18'],
      dtype=object)

In [251]:
##Run trial model
df_subset = df_working.loc[df_working['constructionYear'] != 'None']
X = df_subset[['constructionYear']].values
y = df_subset['price'].values

In [252]:
##Run One Hot Encoder
ohe = OneHotEncoder()
X = ohe.fit_transform(df_subset[['constructionYear']])
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [253]:
##Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [254]:
##Declare instance of model
regressor = LinearRegression()
##Fit the model
regressor.fit(X_train, y_train)
print(regressor.score(X_train, y_train))

0.12148726757757167


In [255]:
##Evaluate the model
y_predict = regressor.predict(X_test)
print(regressor.score(X_test, y_test))
print(regressor.score(X_test, y_predict))

-0.10015494490131926
1.0


In [256]:
##Run trial model (lat, long)
df_lat_long = df_working.loc[df_working['latitude'] != 99.0]

df_lat_long['latitude'] = df_lat_long['latitude'].apply(radians)
df_lat_long['longitude'] = df_lat_long['longitude'].apply(radians)

X = df_lat_long[['latitude', 'longitude']].values
y = df_lat_long['price'].values

C:\Users\ARCH GLOBAL\AppData\Local\Temp\ipykernel_14648\2782714157.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lat_long['latitude'] = df_lat_long['latitude'].apply(radians)
C:\Users\ARCH GLOBAL\AppData\Local\Temp\ipykernel_14648\2782714157.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_lat_long['longitude'] = df_lat_long['longitude'].apply(radians)


In [257]:
##Split the dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [258]:
##Declare instance of model
nbrs = KNeighborsRegressor(weights='distance', metric='haversine')
##Fit the model
nbrs.fit(X_train, y_train)
print(nbrs.score(X_train, y_train))
##Evaluate the model
y_pred = nbrs.predict(X_test)
print(nbrs.score(X_test, y_test))
print(nbrs.score(X_test, y_pred))

0.3506687097317104
0.2700067249120899
1.0
